<?php

define('KIPLE_CARD_ISSUER','AX');
define('KIPLE_CARD_TYPE','CLESS');
define('KIPLE_CARD_EXPIRED_DATE','');

define('KIPLE_ACCOUNT_DEMO','***********2345');
define('KIPLE_TICKET_DEMO','TICKET20181220111111');


define ('ERR_UNKNOWN_RECEIVED_DATA','999');

define('SB_DEVICE_TYPE_ENTRY','1');
define('SB_DEVICE_TYPE_EXIT','2');

define('SB_STATUS_APPROVAL','000');
define('SB_STATUS_IDLE','100');
define('SB_STATUS_INVALID_ACCOUNT','014');
define('SB_STATUS_CARD_INSERT','101');
define('SB_STATUS_CARD_REMOVED','102');
define('SB_STATUS_CARD_IDENTIFICATION','106');
define('SB_STATUS_AUTHORIZATION_APPROVED','112');
define('SB_STATUS_CANCELED','203');
define('SB_STATUS_SERVER_ONLINE','500');
define('SB_STATUS_INITIALIZED','600');
define('SB_STATUS_COMMAND_SUCCESSFUL','900');
